/**
 * Builds the Bankr handler as ONE self-contained TypeScript file with no imports (D-025):
 *   dist/x402/breakra-analyze/index.ts  +  dist/bankr.x402.json
 * Bankr uploads only x402/<service>/index.ts and failed to install npm dependencies in T-001, so
 * api-smart-diff is inlined. The file must end in a literal `export default async function handler`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = join(import.meta.dir, "..");
const outFile = join(root, "dist/x402/breakra-analyze/index.ts");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

// Minified: Bankr's deploy API rejected the 137 KB unminified upload with 413 (Phase 3 T-302).
const result = await Bun.build({
  entrypoints: [join(root, "src/index.ts")],
  target: "bun",
  format: "esm",
  minify: true,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
let code = await (result.outputs[0] as Blob).text();

// The minifier renames the handler; re-export it in the literal form Bankr's wrapper recognises (D-025).
const tail = /export\s*\{\s*([A-Za-z_$][\w$]*)\s+as\s+default\s*\};?\s*$/;
const match = code.match(tail);
if (!match) throw new Error("unexpected bundle tail: expected `export { <name> as default };`");
const inner = match[1] as string;
code = code.replace(tail, "");
if (/\bhandler\b/.test(code))
  throw new Error("bundle already uses the identifier `handler`; cannot add the literal export");
if (/(^|[;}\s])import[\s{(]/.test(code) || /\brequire\(/.test(code))
  throw new Error("bundle still contains imports");
const MAX_BYTES = 92_000; // keep the deploy request well under Bankr's ~100 KB deploy API limit
if (code.length > MAX_BYTES)
  throw new Error(`bundle is ${code.length} bytes; limit ${MAX_BYTES} (Bankr deploy API 413)`);

const header = [
  "// @ts-nocheck",
  `// Breakra ${pkg.version}: GENERATED by scripts/build.ts. Do not edit.`,
  `// Includes api-smart-diff ${pkg.dependencies["api-smart-diff"]} (MIT, (C) Damir Yusipov) and its MIT dependencies.`,
  "",
].join("\n");
const footer = `\nexport default async function handler(req: Request): Promise<Response> {\n  return ${inner}(req);\n}\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + code + footer);

// Bankr service config and listing text (deployed only by the owner via the CLI; never by this script).
const config = {
  network: "base",
  currency: "USDC",
  services: {
    "breakra-analyze": {
      price: "0.02",
      currency: "USDC",
      network: "base",
      paymentScheme: "exact",
      methods: ["POST"],
      description:
        "Compare two OpenAPI 3.0 JSON contracts (inline before/after, up to 1 MB). Returns every change classified breaking / potentially_breaking / unknown / compatible / non_contract, with request/response direction, evidence and a recommended action. Deterministic. Only a 200 is charged; errors are free. Agent guide: https://github.com/danbuildss/breakra/blob/main/SKILL.md",
      schema: {
        input: {
          type: "object",
          properties: {
            before: { type: "object", description: "Previous OpenAPI 3.0.x document (inline JSON)." },
            after: { type: "object", description: "New OpenAPI 3.0.x document (inline JSON)." },
          },
          required: ["before", "after"],
        },
        output: {
          type: "object",
          properties: {
            analysis_id: { type: "string", description: "Same inputs give the same id and result." },
            compatibility: { type: "string", description: "Worst classification across all changes." },
            summary: { type: "object", description: "Counts per classification." },
            changes: { type: "array", description: "Findings with evidence and recommended actions." },
            limitations: { type: "array", description: "What was not analysed (e.g. external $refs)." },
          },
        },
      },
    },
  },
};
writeFileSync(join(root, "dist/bankr.x402.json"), `${JSON.stringify(config, null, 2)}\n`);
console.log(`built ${outFile} (${(header + code + footer).length} bytes)`);
