/**
 * Builds the Bankr handler as ONE self-contained TypeScript file with no imports (D-025):
 *   dist/x402/breakra-analyze/index.ts  +  dist/bankr.x402.json
 * Bankr uploads only x402/<service>/index.ts and failed to install npm dependencies in T-001, so
 * api-smart-diff is inlined. The file must end in a literal `export default async function handler`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = join(import.meta.dir, "..");
const outFile = join(root, "dist/x402/breakra-analyze/index.ts");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const result = await Bun.build({
  entrypoints: [join(root, "src/index.ts")],
  target: "bun",
  format: "esm",
  minify: false,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
let code = await (result.outputs[0] as Blob).text();

const tail = /export\s*\{\s*handler as default\s*\};?\s*$/;
if (!tail.test(code)) throw new Error("unexpected bundle tail: expected `export { handler as default };`");
code = code.replace(tail, "");
if ((code.match(/async function handler\(/g) ?? []).length !== 1)
  throw new Error("expected exactly one `async function handler(`");
code = code.replace("async function handler(", "async function __breakraHandler(");
if (/^\s*import\s/m.test(code) || /\brequire\(/.test(code)) throw new Error("bundle still contains imports");

const header = [
  "// @ts-nocheck",
  `// Breakra ${pkg.version}: GENERATED by scripts/build.ts. Do not edit.`,
  `// Includes api-smart-diff ${pkg.dependencies["api-smart-diff"]} (MIT, (C) Damir Yusipov) and its MIT dependencies.`,
  "",
].join("\n");
const footer =
  "\nexport default async function handler(req: Request): Promise<Response> {\n  return __breakraHandler(req);\n}\n";

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + code + footer);

// Bankr service config for Phase 3 (deployed only with owner approval; never by this script).
const config = {
  network: "base",
  currency: "USDC",
  services: {
    "breakra-analyze": {
      price: "0.02",
      currency: "USDC",
      network: "base",
      paymentScheme: "exact",
      methods: ["POST"],
      description:
        "Compare two OpenAPI 3.0 JSON contracts. Returns each change with a compatibility class (breaking / potentially_breaking / unknown / compatible), request/response direction, evidence and a recommended action. Deterministic. Invalid input returns 4xx and is not charged.",
      schema: {
        input: {
          type: "object",
          properties: {
            before: { type: "object", description: "Previous OpenAPI 3.0.x document (inline JSON)." },
            after: { type: "object", description: "New OpenAPI 3.0.x document (inline JSON)." },
          },
          required: ["before", "after"],
        },
        output: {
          type: "object",
          properties: {
            compatibility: { type: "string", description: "Worst classification across all changes." },
            summary: { type: "object", description: "Counts per classification." },
            changes: { type: "array", description: "Findings with evidence and recommended actions." },
          },
        },
      },
    },
  },
};
writeFileSync(join(root, "dist/bankr.x402.json"), `${JSON.stringify(config, null, 2)}\n`);
console.log(`built ${outFile} (${(header + code + footer).length} bytes)`);
